[package]
name = "piqc"
version = "0.0.0"
authors = ["Patrick Koenig <pkoenig10@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.0"
regex = "1.0.2"

[dev-dependencies]
difference = "2.0.0"

[build-dependencies]
lalrpop = "0.16.0"
