[package]
name = "piqc"
version = "0.0.0"
authors = ["Patrick Koenig <pkoenig10@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.15.0"

[dependencies]
lalrpop-util = "0.15.0"
regex = "0.2.1"
