[package]
name = "piqc"
version = "0.0.0"
authors = ["Patrick Koenig <pkoenig10@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.3"
logos = "0.11.4"
regex = "1.1.2"

[dev-dependencies]
difference = "2.0.0"

[build-dependencies]
lalrpop = "0.16.3"
